language: python

os:
  - linux

python:
  - 2.7
  - 3.6

sudo: false

install:
  - python -m pip install numpy scipy

script:
  - python -c "import scooby; print(scooby.Versions())"
  - python -c "import scooby; print(scooby.Versions(core='numpy'))"
  - python -c "import scooby; print(scooby.Versions(additional=['mock', 'foo']))"
  - python -c "import scooby; print(scooby.Versions(additional=['foo']))"

notifications:
  email:
    recipients:
      - info@pyvista.org
    on_success: never
    on_failure: never

deploy:
  - provider: pypi
    user: banesullivan
    distributions: sdist
    on:
      repo: banesullivan/scooby
      branch: master
      tags: true
      python: 3.6
    password: $PYPI_PASSWORD
